name: Cpp-checker

on:
  push 

jobs:
  Signal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: sudo apt-get install -y valgrind cppcheck
      - name: Gpp Error
        run: g++ -Wall -Werror *.cpp
      - name: Cppchecks Error
        run: cppcheck *.cpp --enable=style --error-exitcode=1
      - name: Error List
        run: cppcheck *.cpp --enable=performance --output-file=cppcheck.txt
      - name: Artifacting
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck
          path: ./cppcheck.txt